// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: cal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CServiceClient is the client API for CService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CServiceClient interface {
	Cal(ctx context.Context, in *CRequest, opts ...grpc.CallOption) (*CResponse, error)
}

type cServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCServiceClient(cc grpc.ClientConnInterface) CServiceClient {
	return &cServiceClient{cc}
}

func (c *cServiceClient) Cal(ctx context.Context, in *CRequest, opts ...grpc.CallOption) (*CResponse, error) {
	out := new(CResponse)
	err := c.cc.Invoke(ctx, "/calculator.CService/Cal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CServiceServer is the server API for CService service.
// All implementations must embed UnimplementedCServiceServer
// for forward compatibility
type CServiceServer interface {
	Cal(context.Context, *CRequest) (*CResponse, error)
	mustEmbedUnimplementedCServiceServer()
}

// UnimplementedCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCServiceServer struct {
}

func (UnimplementedCServiceServer) Cal(context.Context, *CRequest) (*CResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cal not implemented")
}
func (UnimplementedCServiceServer) mustEmbedUnimplementedCServiceServer() {}

// UnsafeCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CServiceServer will
// result in compilation errors.
type UnsafeCServiceServer interface {
	mustEmbedUnimplementedCServiceServer()
}

func RegisterCServiceServer(s grpc.ServiceRegistrar, srv CServiceServer) {
	s.RegisterService(&CService_ServiceDesc, srv)
}

func _CService_Cal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CServiceServer).Cal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CService/Cal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CServiceServer).Cal(ctx, req.(*CRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CService_ServiceDesc is the grpc.ServiceDesc for CService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CService",
	HandlerType: (*CServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cal",
			Handler:    _CService_Cal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cal.proto",
}
