// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/poetry.proto

package poetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Poetry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author    string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Lines     []string `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	Linecount int32    `protobuf:"varint,4,opt,name=linecount,proto3" json:"linecount,omitempty"`
}

func (x *Poetry) Reset() {
	*x = Poetry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poetry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Poetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poetry) ProtoMessage() {}

func (x *Poetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poetry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poetry.ProtoReflect.Descriptor instead.
func (*Poetry) Descriptor() ([]byte, []int) {
	return file_proto_poetry_proto_rawDescGZIP(), []int{0}
}

func (x *Poetry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Poetry) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Poetry) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Poetry) GetLinecount() int32 {
	if x != nil {
		return x.Linecount
	}
	return 0
}

type RandomPoetriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfPoetries int32 `protobuf:"varint,1,opt,name=number_of_poetries,json=numberOfPoetries,proto3" json:"number_of_poetries,omitempty"`
}

func (x *RandomPoetriesRequest) Reset() {
	*x = RandomPoetriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poetry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomPoetriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomPoetriesRequest) ProtoMessage() {}

func (x *RandomPoetriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poetry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomPoetriesRequest.ProtoReflect.Descriptor instead.
func (*RandomPoetriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_poetry_proto_rawDescGZIP(), []int{1}
}

func (x *RandomPoetriesRequest) GetNumberOfPoetries() int32 {
	if x != nil {
		return x.NumberOfPoetries
	}
	return 0
}

type PoetryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Poetry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PoetryList) Reset() {
	*x = PoetryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poetry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoetryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoetryList) ProtoMessage() {}

func (x *PoetryList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poetry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoetryList.ProtoReflect.Descriptor instead.
func (*PoetryList) Descriptor() ([]byte, []int) {
	return file_proto_poetry_proto_rawDescGZIP(), []int{2}
}

func (x *PoetryList) GetList() []*Poetry {
	if x != nil {
		return x.List
	}
	return nil
}

var File_proto_poetry_proto protoreflect.FileDescriptor

var file_proto_poetry_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x06, 0x50,
	0x6f, 0x65, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x6e,
	0x65, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69,
	0x6e, 0x65, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x6f,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x2f,
	0x0a, 0x0a, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32,
	0x54, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x50, 0x6f, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x50, 0x6f, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x65, 0x74, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x37, 0x5a, 0x35, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x65, 0x74, 0x72, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_poetry_proto_rawDescOnce sync.Once
	file_proto_poetry_proto_rawDescData = file_proto_poetry_proto_rawDesc
)

func file_proto_poetry_proto_rawDescGZIP() []byte {
	file_proto_poetry_proto_rawDescOnce.Do(func() {
		file_proto_poetry_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_poetry_proto_rawDescData)
	})
	return file_proto_poetry_proto_rawDescData
}

var file_proto_poetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_poetry_proto_goTypes = []interface{}{
	(*Poetry)(nil),                // 0: proto.Poetry
	(*RandomPoetriesRequest)(nil), // 1: proto.RandomPoetriesRequest
	(*PoetryList)(nil),            // 2: proto.PoetryList
}
var file_proto_poetry_proto_depIdxs = []int32{
	0, // 0: proto.PoetryList.list:type_name -> proto.Poetry
	1, // 1: proto.ProtobufService.RandomPoetries:input_type -> proto.RandomPoetriesRequest
	2, // 2: proto.ProtobufService.RandomPoetries:output_type -> proto.PoetryList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_poetry_proto_init() }
func file_proto_poetry_proto_init() {
	if File_proto_poetry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_poetry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Poetry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poetry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomPoetriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poetry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoetryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_poetry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_poetry_proto_goTypes,
		DependencyIndexes: file_proto_poetry_proto_depIdxs,
		MessageInfos:      file_proto_poetry_proto_msgTypes,
	}.Build()
	File_proto_poetry_proto = out.File
	file_proto_poetry_proto_rawDesc = nil
	file_proto_poetry_proto_goTypes = nil
	file_proto_poetry_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProtobufServiceClient is the client API for ProtobufService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProtobufServiceClient interface {
	RandomPoetries(ctx context.Context, in *RandomPoetriesRequest, opts ...grpc.CallOption) (*PoetryList, error)
}

type protobufServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtobufServiceClient(cc grpc.ClientConnInterface) ProtobufServiceClient {
	return &protobufServiceClient{cc}
}

func (c *protobufServiceClient) RandomPoetries(ctx context.Context, in *RandomPoetriesRequest, opts ...grpc.CallOption) (*PoetryList, error) {
	out := new(PoetryList)
	err := c.cc.Invoke(ctx, "/proto.ProtobufService/RandomPoetries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtobufServiceServer is the server API for ProtobufService service.
type ProtobufServiceServer interface {
	RandomPoetries(context.Context, *RandomPoetriesRequest) (*PoetryList, error)
}

// UnimplementedProtobufServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProtobufServiceServer struct {
}

func (*UnimplementedProtobufServiceServer) RandomPoetries(context.Context, *RandomPoetriesRequest) (*PoetryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomPoetries not implemented")
}

func RegisterProtobufServiceServer(s *grpc.Server, srv ProtobufServiceServer) {
	s.RegisterService(&_ProtobufService_serviceDesc, srv)
}

func _ProtobufService_RandomPoetries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomPoetriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtobufServiceServer).RandomPoetries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProtobufService/RandomPoetries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtobufServiceServer).RandomPoetries(ctx, req.(*RandomPoetriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProtobufService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProtobufService",
	HandlerType: (*ProtobufServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RandomPoetries",
			Handler:    _ProtobufService_RandomPoetries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/poetry.proto",
}
